### ISSUE TITLE
Fluency supports an option to save remaining memory buffer to file when stopping

### ISSUE THREAD

**Issue by komamitsu** [komamitsu/fluency#10]
Even with ACK response mode enabled, Fluency can lost buffered data when `Fluency#close` method is called, but Fluentd is down and Fluency retries over.

In this case, the following option sounds helpful to avoid data lost:

1. Fluency saves buffered memory data to a specified file path if the option is enabled when it gives up flushing the data after `Fluency#close` method is called

2. Fluency loads the file to its memory buffer when launching if the option is enabled

**Comment by repeatedly** [comment]
Could you release new version?

**Comment by komamitsu** [comment]
@repeatedly Okay. I'll release new version tomorrow if possible.
