### ISSUE TITLE
Copyright and license in the class files headers

### ISSUE THREAD

**Issue by xnike** [komamitsu/fluency#101]
Hi Mitsunori Komatsu,

We would very much like to use your project as 3rd-party library, but we can't for the law reasons  - a missing copyright and license header in the class files. 
Could you please  add them to  a new minor release?

**Comment by komamitsu** [comment]
Hi @xnike 

I added license header to source files at https://github.com/komamitsu/fluency/pull/102 and just released them as 1.8.1

**Comment by xnike** [comment]
Thank you a lot
