### ISSUE TITLE
2038 year problem of EventTime (int seconds)

### ISSUE THREAD

**Issue by xerial** [komamitsu/fluency#104]
https://github.com/komamitsu/fluency/blob/master/src/main/java/org/komamitsu/fluency/EventTime.java#L33-L34

EventTime uses 32-bit singed integers, and it will hit the limit at `2038-01-18 19:14:07+00:00`  (= unixtime of 2^31 - 1)

If we use long for epoch seconds (to support uint32), the limit can be extended to `2106-02-06 22:28:15+00:00`.

**Comment by komamitsu** [comment]
Good catch! Thanks for reporting it.
