### ISSUE TITLE
[Feature] Support shared key or TLS client certificates

### ISSUE THREAD

**Issue by jcassee** [komamitsu/fluency#106]
As per the title, it would be useful to be able to access a protected Fluentd endpoint.

**Comment by ssozonoff** [comment]
TLS support seems to be their ... can find support for Shared Secret however

**Comment by komamitsu** [comment]
@jcassee You can use client certificates with Fluency. Try `-Djavax.net.ssl.keyStore`.
Also, https://banzaicloud.com/blog/k8s-logging-tls/ is really useful to know how to prepare files and configurations for that.

**Comment by jcassee** [comment]
@komamitsu Cool, thanks!

So that leaves shared secrets I guess.

**Comment by komamitsu** [comment]
I might be missing something from your mentions to `shared secrets`.  What does `shared secrets` exactly mean in the context? I think SSL/TLS uses shared secrets as a part of them.

**Comment by jcassee** [comment]
> I think they call it shared_key

Yes, that is what I meant.

**Comment by komamitsu** [comment]
I see. I thought it was SSL/TLS's one. Thanks for the correction.

As for Fluentd's `shared key` feature. I don't have a plan to support it for now since client certifications are basically better in that we don't need to manage a shared key by ourselves.

**Comment by jcassee** [comment]
@komamitsu Okay, fair enough. Shall we close this issue then?

**Comment by komamitsu** [comment]
Yes. And thanks for letting me know Fluentd's `shared key`. I'll reopen this issue in the future if we need it.
