### ISSUE TITLE
TLS issues, possible Bug

### ISSUE THREAD

**Issue by ssozonoff** [komamitsu/fluency#117]
Hi,

SSLSocketBuilder.java

`          SSLContext sslContext = SSLContext.getInstance(SSL_PROTOCOL);
            sslContext.init(null, null, new SecureRandom());`

Why are you creating a new context instead of using the default one ? The above sets the keystore and truststore to null so we are unable to pass them in from the command line.

**Comment by komamitsu** [comment]
Thanks for reporting it. I'm a bit too busy to look into it now. But I'll take care of it later.

**Comment by komamitsu** [comment]
Indeed, we can use the default SSLContext so that it gets more simple. But with the original code, I confirmed we successfully passed a truststore via command line like `-Djavax.net.ssl.trustStore=/path/to/truststore.jks`.

> we are unable to pass them in from the command line

Could you tell me the details of what your problem is?

**Comment by ssozonoff** [comment]
I dont have more information but we were unable to make it work with the above and using a debugger always ended up with an empty value for the keystore and truststore. We in any case had to steer away from this option because there is no support for the shared secret.

Kind thanks
