### ISSUE TITLE
What is the minimum Wait values to flush 

### ISSUE THREAD

**Issue by dbarriguete** [komamitsu/fluency#138]
I have implemented code and it works OK.
I need to reduce execution time on my app and when added Fluency to my code it takes more time to complete.

I changed wait values as follows:

```// Single Fluentd(localhost:24224
)
//   - Max wait until all buffers are flushed is 10 seconds
//   - Max wait until the flusher is terminated is 15 seconds
FluencyBuilderForFluentd builder = new FluencyBuilderForFluentd();
builder.setWaitUntilBufferFlushed(10);
builder.setWaitUntilFlusherTerminated(15);
```

Using this configuration Fluency doesn't log anything, I suppose this is because it needs more time, but how do I know what is the mínimum value that I may place? or arguments are in milliseconds?

Regards 
Diego Barriguete

**Comment by dbarriguete** [comment]
Is it OK if I change those values to 1 second?
What are these variables created for?

**Comment by komamitsu** [comment]
What did you mean by `execution time`?

> builder.setWaitUntilBufferFlushed(10);

Even if you set these configurations to larger figures, Fluency should finish immediately when `Fluency#close()` is called and then all buffers are flushed.

Could you give me a minimum code that can reproduce the issue?

**Comment by komamitsu** [comment]
I'm closing this issue. Feel free to reopen if you still have a trouble.
