### ISSUE TITLE
Issue when used with spring-cloud-sleuth.

### ISSUE THREAD

**Issue by devportilla** [komamitsu/fluency#145]
Hello
When using fluency on a spring boot project in conjunction with spring-cloud-starter & a non available host the application startup hangs for a while without an apparent reason.
My guess is that during spring startup when  a buffer flush is being triggered something happens in between and blocks the execution of the rest of the startup.

Any help will be appreciated.

**Comment by komamitsu** [comment]
Could you give me some more information?

1. The issue happened even w/o calling `Fluency#emit()`?
2. What happened with an available host?
3. JVM thread dump

**Comment by komamitsu** [comment]
I'm closing this issue. Feel free to reopen if you still have a trouble.
