### ISSUE TITLE
EventTime: any reason seconds isn't an int?

### ISSUE THREAD

**Issue by ljnelson** [komamitsu/fluency#151]
Thanks for a great project.

What is the reason for `seconds` in `EventTime` to be a 64-bit-`long`-that-is-only-valid-if-in-fact-it-is-a-32-bit-`int` rather than just an `int`?  I assume it's performance related?

**Comment by komamitsu** [comment]
Just because I don't want to have a concern of overflow with `int` in 2038 or later not performance related.

BTW, I didn't completely get what you meant by `64-bit-long-that-is-only-valid-if-in-fact-it-is-a-32-bit-int`. What do you mean with that?

**Comment by ljnelson** [comment]
Thanks for your answer!

What I meant was: you are using 32 bits of a `long` to represent an `int`.  If I give you a `long` that uses more than 32 bits, you reject it, suggesting that `long` is the wrong kind of datatype to use here.  Now at least I understand your reasoning.  Thanks again.

**Comment by komamitsu** [comment]
I just got your point and noticed I forgot the validation of 32 bit value, LoL
