### ISSUE TITLE
Logback.xml Sample

### ISSUE THREAD

**Issue by sreyasvpariyath** [komamitsu/fluency#161]
Hi,
I am currently using sl4j in my spring boot micro services. I would like to integrate fluentd with my services.Currently I am using fluent-logger  in my logback xml as an appender and propagate the logs to Fluentd. Since it does not support SSL, I would like to explore Fluency. Can Fluency be defined as an appender in my logback.xml with ssl enabled.?

**Comment by komamitsu** [comment]
I just found https://github.com/sndyuk/logback-more-appenders that's support Fluency. It seems to support SSL https://github.com/sndyuk/logback-more-appenders/blob/master/src/test/resources/logback-appenders-fluentd.xml#L94. I think it's worth trying it.

**Comment by sreyasvpariyath** [comment]
Thanks for you response.. One more doubt.. If I keep ssl flag as enabled,How/where can I specify the ssl related information such as certficate/key path..etc

**Comment by sreyasvpariyath** [comment]
Hi, 
I have made a sample project regarding this. If anyone want to use fluentd in spring boot can have a look at it. Whatever I have done is furnished in the readme. When I started I was kind of clue less about where to start, so I made this repo for those who are at a beginner level like me..
https://github.com/sreyasvpariyath/Pub-Workspace/tree/master/fluentd.springboot.ssl
