### ISSUE TITLE
What happens when Fluentd Server is down.?

### ISSUE THREAD

**Issue by sreyasvpariyath** [komamitsu/fluency#162]
We are planning to integrate Fluentd with our services. So Logging across the services is always been the challenge.

As a first step, Now we are planning to integrate Fluentd with all our micro-services. While reading about the limitation of fluent-logger we have decided to go with Fluency Thanks a lot for an awesome project. 

Since we are interested in integrate Fluency with our services, We would like to know more about Fluency. Like the main point is, 

-What happens if the Fluentd Server is down.?
    -Does it has a buffer.? if yes what is the default size.? and how do we specify it.?
-How does the communication between fluency and fluentd-server communication been managed.?
-Would it be a bottleneck for the application performance if we have not taken care of any particular configuration?

Currently we are using logback.xmls across all over the services. We are looking an approach where we could just add a fluentd appender in it and Fluency dependencies in the pom.xml.

Could you please help by providing necessary details.?

Thanks

**Comment by komamitsu** [comment]
Thanks for using Fluency! Our company (Arm Treasure Data) is also
using it heavily in production 😉 

> What happens if the Fluentd Server is down.?
> Does it has a buffer.? if yes what is the default size.? and how do we specify it.?

Fluency buffers data in memory until the Fluentd gets up. How much it can buffer depends on the configuration of `MaxBufferSize` (see also https://github.com/komamitsu/fluency#for-high-throughput-data-ingestion-with-high-latency)

> How does the communication between fluency and fluentd-server communication been managed.?

When the destination Fluentd is a single node, Fluency just sends data to it and keeps data in memory if it failed.

When using multiple Fluentd nodes, Fluency does:
- heartbeat with them via TCP/UDP to detect unavailable nodes in advance
- send data to the secondary node while the primary node is down

> Would it be a bottleneck for the application performance if we have not taken care of any particular configuration?

Default configurations of Buffer might be a bit small if you use Fluency for high throughput usage. https://github.com/komamitsu/fluency#for-high-throughput-data-ingestion-with-high-latency would be a good example. Note that throughput and latency are kind of trade off.

**Comment by sreyasvpariyath** [comment]
What will happen if the Buffer is full.? Will flush the whole data or it will start over writing.?
```java
builder.setBufferChunkInitialSize(16 * 1024 * 1024);
builder.setBufferChunkRetentionSize(64 * 1024 * 1024);
builder.setMaxBufferSize(1024 * 1024 * 1024L);
```
Could you please elaborate the purpose and functionality of these parameters.?
