### ISSUE TITLE
Support to HTTP Input

### ISSUE THREAD

**Issue by luizgustavoss** [komamitsu/fluency#166]
I've searched a bit and couldn't find an answer to this. 
Does fluency (or even fluent-logger-java) support sending logs to http endpoint, when fluentd server has [in_http Input Plugin](https://docs.fluentd.org/input/http) enabled?

**Comment by komamitsu** [comment]
I don't have a plan to support in_http protocol / format in Fluency at the moment. Fluency is for high throughput data ingestion, but I don't think in_http isn't so good choice for the purpose. As for fluent-logger-java, I also don't think it'll support in_http.
