### ISSUE TITLE
Architectural Doubts

### ISSUE THREAD

**Issue by luizgustavoss** [komamitsu/fluency#167]
Hi! 

I don't know if this is the best place to ask such questions, please let me know if there's a better place.
I've considered Fluentd as a key component of an audit architecture design. I have some questions regarding _fluency/fluent-logger-java_, but let me first explain the context.

I need to collect logs in many services, so to easy the developers lives I created a library to abstract most work related to format output logs and validate data, besides connection to Fluentd server.

![arquitetura-auditoria-Page-6](https://user-images.githubusercontent.com/5515537/84843244-baa2e800-b01d-11ea-90bc-100b1e32aab2.png)

The service can programmatically call audit in the lib or rely on automatic capture of events, and in the library both strategies send the final formatted data to fluentd client (in this diagram **fluent-logger-java**, as it was my first option at the time). The client sends data to fluentd server, that sends logs to S3 and so on.

In a deployment point of view, I would like to have this:

![arquitetura-auditoria-Page-7](https://user-images.githubusercontent.com/5515537/84846432-2e94be80-b025-11ea-85cf-0df0e1fffe05.png)

Services running on EC2 would  call a Fluentd cluster, whereas microservices would rely on a side-car instance of fluentd, so I could distribute load.  

## Questions

Given the above context, I have some questions.

1) Initially I've tested with TPC input on port 24224, but when deploying Fluentd in Kubernetes we had to use **_in_http Input Plugin_**, and I noticed that **fluent-logger-java** didn't support such communication, so I'd like to know: **is there an option for such input option with fluency?**

2) Considering the implementation of my library still relies on **fluent-logger-java** (I'm considering to change to Fluency),  is it ok to create a FluentLogger for each log operation, closing it at the end? Notice that I even create a new thread to do the call, so I don't lock the current thread if calling Fluentd has a high timeout. Is this the best way to do this with **Fluency**?

```java
public class FluentdAuditLogWriter implements AuditLogWriter {

    private final AuditConfiguration auditConfiguration;

    @Override
    public boolean audit(AuditRecordMap auditRecordMap) {

        if(!hasValidaData(auditRecordMap) || !hasRequiredParameters())
            return false;

        FluentdLogWorker worker = new FluentdLogWorker(
                this.auditConfiguration.getApplicationName(),
                this.auditConfiguration.getFluentdServerHost(),
                this.auditConfiguration.getFluentdServerPort(),
                this.auditConfiguration.getFluentdTagPrefix(),
                this.auditConfiguration.getFluentdTag(),
                auditRecordMap);

        new Thread(worker).start();

        return true;
    }

    private boolean hasValidaData(AuditRecordMap auditRecordMap){
        ...
    }

    private boolean hasRequiredParameters(){
        ...
    }

    class FluentdLogWorker implements Runnable {

        private final String tagPrefix;
        private final String serverHost;
        private final String tag;
        private final int serverPort;
        private String applicationName;
        private final AuditRecordMap auditRecordMap;

        FluentdLogWorker(String applicationName, String serverHost, int serverPort, String tagPrefix, String tag,
                         AuditRecordMap auditRecordMap){
            this.applicationName = applicationName;
            this.serverHost = serverHost;
            this.serverPort = serverPort;
            this.tagPrefix = tagPrefix;
            this.tag = tag;
            this.auditRecordMap = auditRecordMap;
        }

        public void run() {
            FluentLogger logger = null;
            try{
                logger = FluentLogger.getLogger(this.tagPrefix,
                        this.serverHost, this.serverPort);
                logger.log(this.tag, auditRecordMap.getAuditRecordMap());
            } catch(Throwable t){
                log.error("[AUDIT] Error logging audit data (FluentdLogWorker)! Details: {}", t.getMessage());
            } finally {
                if(logger != null)
                    logger.close();
            }
        }
    }
}
```

3) What is the best way to handle connection erros with Fluency? 

4) What's the recommended way to backup data in local disk when communication erros occur and the way to send it later?

5) My intention is to have some instances of Fluentd behind a load balancer and make Fluency communicate with LB. Is that possible, or just with TCP and [failover configuration](https://github.com/komamitsu/fluency#for-multiple-fluentd-with-failover)?

**Comment by komamitsu** [comment]
> 1
fluent-logger-java and Fluency don't support in_http since the protocols of in_forward and in_http are completely different.

> 2
FluentLogger.getLogger() weakly caches FluentLogger instances, so it seems to work well since it can avoid instantiating an FluentLogger and underlaying objects every call. Fluency library doesn't have this kind of cache mechanism, but I think you can implement a similar thing.

> 3
When Fluency faces TCP connection errors and so on, it retries sending buffered data until it sends successfully in a background thread so that the application won't be blocked.

> 4
Fluency has a feature to persistent buffered data in local disk when the application is shut down. See https://github.com/komamitsu/fluency#enable-file-backup-mode

> 5
If you're interested in load balance of Fluentd servers, putting a load balancer in front of them is the best way, I think.
