### ISSUE TITLE
Regarding setSenderWorkBufSize and setJvmHeapBufferMode(true);

### ISSUE THREAD

**Issue by sreyasvpariyath** [komamitsu/fluency#169]
I have been trying to optimize fluency config for better performance, I came across few parameter which I could not find any details 
anywhere. 
`setSenderWorkBufSize and setJvmHeapBufferMode(true);`
Could you please explain how these parameters works.?

**Comment by komamitsu** [comment]
`setSenderWorkBufSize()` exists only in `FluencyBuilderForAwsS3` and `FluencyBuilderForTreasureData` not in `FluencyBuilderForFluentd`, so if you use Fluency to ingest data to Fluentd you don't need to think of the method.

As for `setJvmHeapBufferMode()`, Fluency uses off-heap memory buffer that's not in JVM's heap by default and calling the method with `true` makes Fluency allocate memory for buffering in JVM heap memory. With `setJvmHeapBufferMode(true)` you could avoid unexpectedly consuming OS's memory, but you might run into `java.lang.OutOfMemoryError`
