### ISSUE TITLE
Can we customize the size of data sent?

### ISSUE THREAD

**Issue by brieuc-le-faucheur** [komamitsu/fluency#170]
Hello,
I have setup Fluency fluentd appender to send my app logs to a fluent-bit instance, which sometimes logs a warning:
`[2020/07/29 14:40:12] [ warn] [input:forward:forward.0] fd=21 incoming data exceed limit (32768 bytes)`.
As it seems like I cannot change this on the fluent-bit side, I browsed the fluency fluentd appender code but I did not find any way to tune the size of the output data sent. Is there any way to achieve this?
Thanks

Edit: I managed to customize the entry reading buffer size on fluent bit side in the end, but I am still interested in the info about fluency output data size

**Comment by komamitsu** [comment]
Sorry for my late reply.

I think you can control the maximum data size Fluency sends at once by adjusting these parameters like this

```
FluencyBuilderForFluentd builder = new FluencyBuilderForFluentd();
builder.setBufferChunkInitialSize(16 * 1024); // 16KB
builder.setBufferChunkRetentionSize(24 * 1024); // 24KB. This is a threshold not a strict limitation, so it's should be less than 32KB
```

**Comment by 1pkt** [comment]
Hi!

Thanks for the answer, and sorry for my also late reply. I managed to find a way to control the input buffer on the fluentbit side, so it is possible in the end. I will try to think about it next time I face the problem.

**Comment by komamitsu** [comment]
I'm closing this issue, but feel free reopen it if needed
