### ISSUE TITLE
emit map date issure

### ISSUE THREAD

**Issue by zhyang0918** [komamitsu/fluency#180]
I put date mongo：
Map<String, Object> map = new HashMap<>();
map.put("date", LocalDateTime.now());
fluency.emit("mongo.test.date", map);
but mongo data like is :
{
    dayOfMonth: NumberInt("12"),
    dayOfWeek: "THURSDAY",
    dayOfYear: NumberInt("317"),
    month: "NOVEMBER",
    monthValue: NumberInt("11"),
    year: NumberInt("2020"),
    hour: NumberInt("16"),
    minute: NumberInt("14"),
    nano: NumberInt("915000000"),
    second: NumberInt("5"),
    chronology: {
        id: "ISO",
        calendarType: "iso8601"
    }
}
emit data format？
use official : 
FluentLogger.log("tag", map);
mongo data like is :
2020-11-12T16:18:34.227
i need help. thks

**Comment by komamitsu** [comment]
You can use `com.fasterxml.jackson.datatype:jackson-datatype-jsr310`

```
   objectMapper
     .disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)
     .registerModule(new JavaTimeModule());
```

**Comment by zhyang0918** [comment]
thanks,i'll try it
