### ISSUE TITLE
Cannot use mutual signing TLS

### ISSUE THREAD

**Issue by rymiel** [komamitsu/fluency#184]
I've created a self-signed certificate to act as a CA and two certificates that are signed by this CA, of which one is given to the fluentd server and the other is put into the keystore of the Fluency

fluentd.conf:
```xml
<source>
  @type forward
  @id forward_input

  port 24224
  bind 0.0.0.0
  <transport tls>
    version                TLSv1_2
    ca_path                /etc/ssl/fluentd/ca.crt.pem
    cert_path              /etc/ssl/fluentd/server.crt.pem
    private_key_path       /etc/ssl/fluentd/server.key.pem
    private_key_passphrase <snip>
    client_cert_auth       true
  </transport>
</source>
```

i'm building the fluency object like this
```java
    FluencyBuilderForFluentd builder = new FluencyBuilderForFluentd();
    builder.setSslEnabled(true);
    fluency = builder.build("<external server>", 24224);
```

Enabling debugging using -Djavax.net.debug=all shows `javax.net.ssl|DEBUG|2C|pool-4-thread-1|2021-04-05 22:57:27.269 EEST|CertificateMessage.java:299|No X.509 certificate for client authentication, use empty Certificate message instead` while fluentd logs show `unexpected error before accepting TLS connection by OpenSSL error_class=OpenSSL::SSL::SSLError error="SSL_accept returned=1 errno=0 state=error: peer did not return a certificate"`.

Note that I'm able to use the same certificates (in PEM format) to connect and communicate with the fluentd server using `openssl s_client`, with proper authentication given.

It's clear the Fluency client isn't returning a client certificate, but I cannot figure out why. Has anyone even been able to use mutual certificates using fluency? In #106 you've mentioned they're supported but give no direct documentation how it works for this java library, and also neglect shared secrets. Similarly, #117 has problems with mutual certificates and gives up on the library because of lack of shared secrets. Having spent a couple of days trying to figure out SSL I'd rather take the seemingly much simpler shared secrets for **secure logging to an external server**, which doesn't seem to be covered by any sort of java library.

**Comment by komamitsu** [comment]
@rymiel Sorry for my late reply. 

In this case, I think you need to specify both `truststore` and `keystore` in addition to  https://github.com/komamitsu/fluency#send-requests-over-ssltls. If you've already tried with custom `truststore` and `keystore`, could you give me how you created and passed
them to Fluency?

**Comment by komamitsu** [comment]
I've reproduced this issue using https://github.com/komamitsu/fluentd-mutual-tls-example.

I found Fluency side sent an empty `Certificates` in TLS handshake. I guess the keystore file specified via `-Djavax.net.ssl.keyStore` isn't used expectedly. I'll continue to investigate it.
