### ISSUE TITLE
Many ESTABLISHED sockets on server sidew hile using fluency

### ISSUE THREAD

**Issue by jondoe1337** [komamitsu/fluency#22]
Created this issue for public knowledge, after having mail contact with komamitsu:

The problem we currently notice is that the server has a rising number of ESTABLISHED sockets to the hosts with the JVM, that log with fluency. All sockets are connected to the in_forward.
On the server side we use the td-agent 2.3.1 on a Ubuntu 14.04 LTS.

The clients still have only one ESTABLISHED. The cluent fluency version is the 0.0.9 artifact from the mvn repo.

The solution is to restart the td-agent every 2 days as it will crash because of reaching the ulimit.

We are instantiating the fluency connection like this:
```
Fluency logger = Fluency.defaultFluency(config.getServerIp(), config.getServerPort());
```
This logger instance is accessible via a static Holder instance. So it's just one instance per JVM.

The only methods that are invoked on this object are (This is called via a Runtime ShutdownHook):
```
logger().close();
                for (int i = 0; i < 5; i++)
                {
                    if (logger().isTerminated())
                    {
                        break;
                    }
                    TimeUnit.SECONDS.sleep(5);
                }
```

The other call is:
```
Map<String, Object> log = new HashMap<String, Object>();
log.put(PROCESS_PROP, processIdentifier);
log.put(HOST_PROP, hostAlias);
log.put(ENVIRONMENT_PROP, environment);
log.put(MESSAGE_PROP, String.format(format, objects));
logger().emit(getName(), log);
//whereas getName() returns a string
```

The server-config of the td-agent is:
```
 <source>
    @type forward
    port 24224
  </source>
  <match **>
    type elasticsearch
    host localhost
    port 9200
    include_tag_key true
    logstash_format true
    flush_interval 3s
  </match>
```

**Comment by komamitsu** [comment]
@jondoe1337 Thank you for writing it down here.
I tried to reproduced this issue and executed a similar test for a few days. But I can't reproduce it...

Could you tell me the result of `ss -n` or `netstat -nt` command on the client side? Of course, you can mask real IP addresses if needed.

**Comment by jondoe1337** [comment]
Here is the ss output - changed the ips to client + logger (td-agent) pseudo-hostname:
``
Netid  State      Recv-Q Send-Q                                                                                       Local Address:Port                                                                                         Peer Address:Port 
u_str  ESTAB      0      0                                                                                                        * 490670174                                                                                                   * 0    
u_str  ESTAB      0      0                                                                                                        * 490669028                                                                                                   * 0    
tcp    ESTAB      0      0                                                                                        ::ffff:172.17.0.2:49401                                                                                ::ffff:logger-host:24224 
tcp    ESTAB      0      0                                                                                        ::ffff:172.17.0.2:47228                                                                              ::ffff:client-host:5672  
``

What is confusing is, that a lsof output shows multiple lines of:
``
java      5     root  195u  IPv6          490667801      0t0       TCP ca8fcc745834:49401->logger-host:24224 (ESTABLISHED)
``

The client runs inside a docker container.

**Comment by komamitsu** [comment]
@jondoe1337 
What command and options did you use to check TCP connections on server side? Can I ask you to show the result?

**Comment by jondoe1337** [comment]
I used `lsof`
``
td-agent 22998 root 7904u  IPv4 130505838      0t0       TCP 10.2.0.4:24224->logging-client:41307 (ESTABLISHED)
td-agent 22998 root 7908u  IPv4 130502157      0t0       TCP 10.2.0.4:24224->logging-client:57634 (ESTABLISHED)
td-agent 22998 root 7938u  IPv4 130504369      0t0       TCP 10.2.0.4:24224->logging-client:44271 (ESTABLISHED)
td-agent 22998 root 7942u  IPv4 130502315      0t0       TCP 10.2.0.4:24224->logging-client:56062 (ESTABLISHED)
td-agent 22998 root 8107u  IPv4 130532848      0t0       TCP 10.2.0.4:24224->logging-client:41311 (ESTABLISHED)
td-agent 22998 root 8110u  IPv4 130534807      0t0       TCP 10.2.0.4:24224->logging-client:56064 (ESTABLISHED)
td-agent 22998 root 8120u  IPv4 130534963      0t0       TCP 10.2.0.4:24224->logging-client:44275 (ESTABLISHED)
td-agent 22998 root 8123u  IPv4 130535079      0t0       TCP 10.2.0.4:24224->logging-client:57640 (ESTABLISHED)
td-agent 22998 root 8292u  IPv4 130563359      0t0       TCP 10.2.0.4:24224->logging-client:41315 (ESTABLISHED)
td-agent 22998 root 8305u  IPv4 130563598      0t0       TCP 10.2.0.4:24224->logging-client:56068 (ESTABLISHED)
td-agent 22998 root 8313u  IPv4 130563716      0t0       TCP 10.2.0.4:24224->logging-client:44279 (ESTABLISHED)
td-agent 22998 root 8315u  IPv4 130554723      0t0       TCP 10.2.0.4:24224->logging-client:57644 (ESTABLISHED)
td-agent 22998 root 8479u  IPv4 130592773      0t0       TCP 10.2.0.4:24224->logging-client:41319 (ESTABLISHED)
td-agent 22998 root 8494u  IPv4 130587503      0t0       TCP 10.2.0.4:24224->logging-client:56072 (ESTABLISHED)
``

**Comment by komamitsu** [comment]
Thanks and sorry for frequent questions.

1. While the result of `lsof` command on server side shows many connections with `logging-client`, `ss -n` and `lsof` commands on the `logging-client` instance show only one connection?

2. Could you check when those connections were created on server side like this? Please replace `333.333.333.333` with the IP address of `logging-client`.
    ```
$ for fd in `sudo lsof -n -i:24224 -sTCP:ESTABLISHED | grep 333.333.333.333 | awk '{print $4}' | perl -pe 's/(\d+)u/$1/g'`; do sudo ls -l /proc/`sudo lsof -n -i:24224 -sTCP:ESTABLISHED | grep 333.333.333.333 | awk '{print $2}'`/fd/$fd; done
lrwx------ 1 td-agent td-agent 64 May  4 08:14 /proc/12956/fd/57 -> socket:[12341234]
    ```

3. Is it possible to try that without docker?

**Comment by jondoe1337** [comment]
1. Yes, [here](http://pastebin.com/f1MpPnMt) the output.

2. There needs to be the '*' added in the perl cmd. And i replaced the cmd inside of the do clause with the process-id of the td-agent. I've pasted the std::out + std::err to [pastebin](http://pastebin.com/94FJwdPB).

3. Yes we could do that, but I would like to try that as a last step.

**Comment by komamitsu** [comment]
Thanks! All connections were created at 2016-05-03 08:17. What happened at that time?

Also, I'd like to know the status of those sockets. Could you share the result of this command. I believe the td-agent has pid 22998.
```
$ sudo perl -ne 'print if /^\s+\d+:\s+\w+:5EA0\s/' /proc/22998/net/tcp
   2: 00000000:5EA0 00000000:0000 0A 00000000:00000000 00:00000000 00000000   403        0 26964 1 ffff8800e69d0d00 100 0 0 10 -1
  14: 0100007F:5EA0 0100007F:13CC 01 00000000:00000000 00:00000000 00000000   403        0 4814501 1 ffff8800ac2d4e00 20 4 32 10 -1
  17: 0100007F:5EA0 0100007F:13C7 01 00000000:00000000 00:00000000 00000000   403        0 4814494 1 ffff8800e6b8e800 20 4 32 10 -1
  22: 0100007F:5EA0 0100007F:13C6 01 00000000:00000000 00:00000000 00000000   403        0 4814492 1 ffff8800e6b88680 20 4 12 10 -1
```

**Comment by jondoe1337** [comment]
I guess there was the restart of the client.

I've executed to cmd and put it again on [pastebin](http://pastebin.com/6GmBjpsK). Although you must know that the td-agent was restarted this morning.

**Comment by komamitsu** [comment]
Unfortunately, I can't reproduce this issue. According to information from you, the strange points are these ones:
- td-agent had a lot of ESTABLISHED connections to some client side instances
- Those connections were created at once. You guess it was at client side restart
- But each client side instance had only one established connection

One possibility is that the client applications crashed many times even w/o sending RST or FIN packet to td-agent after establishing a connection and td-agent didn't detect there was no process connecting the connection on client side and kept a lot of ESTABLISHED connections.

When you try without docker, please let me know the result.

**Comment by jondoe1337** [comment]
Okay, I will test it without docker, maybe at the end of the week.

**Comment by jondoe1337** [comment]
Final got a chance to test my application scenario without using docker.

But unfortunately we got the same 'results'. 

On client side, lsof -n shows [this](http://pastebin.com/i1i8dx3L).

On server side, lsof shows:

<code>
td-agent 61667 root 9504u  IPv4 172040327      0t0       TCP 10.2.0.4:24224->client-ip:39306 (ESTABLISHED)
td-agent 61667 root 9644u  IPv4 172062705      0t0       TCP 10.2.0.4:24224->client-ip:39348 (ESTABLISHED)
td-agent 61667 root 9645u  IPv4 172063073      0t0       TCP 10.2.0.4:24224->client-ip:39350 (ESTABLISHED)
<code>

I know that java must apply for special tcp socket settings, so i think our settings that we made on the server are not used by the td-agent:
<code>
root@logging:/proc/sys/net/ipv4# cat tcp_keepalive_time
60
root@logging:/proc/sys/net/ipv4# cat tcp_keepalive_intvl
5
root@logging:/proc/sys/net/ipv4# cat tcp_keepalive_probes
6
<code>

**Comment by komamitsu** [comment]
Thanks for the information.

According to the socket list of client side, the port address was 39383. But there was no connection on server side that was connecting to client port 39383. Is there NAT gateway or something between client and server instances?

**Comment by jondoe1337** [comment]
Well the td-agent is running on an azure cloud-server, accessible through a public ip.
The client is running in a private office network behind a fritzbox router...so yes there is a NAT inbetween. :-/

**Comment by jondoe1337** [comment]
Is there any further advice you may give? Maybe I should ask in the github.com/fluent/fluentd project for a serverside help?

**Comment by komamitsu** [comment]
To isolate the cause of this issue, please try the followings

1) Run this minimum code that uses Fluency for a while and see if this issue is reproduced
```java
    public static void main(String[] args)
            throws IOException, InterruptedException
    {
        Fluency fluency = Fluency.defaultFluency("fluentd.hostname");

        Map<String, Object> event = new HashMap<>();
        event.put("name", "foo bar");
        event.put("age", 42);
        while (true) {
            fluency.emit("hello.world", event);
            TimeUnit.SECONDS.sleep(1);
        }
    }
```

 2) Try the other fluent-logger library (e.g. fluent-logger-ruby)
```
$ gem install fluent-logger
$ ruby -r fluent-logger -e "x = Fluent::Logger::FluentLogger.new(nil, :host=>'fluentd.hostname', :port=>24224); loop { x.post('hello.world', {:name => 'foo bar', :age => 42}); sleep 1 }"
```

And then check the number of connections as well. If the second one reproduces this issue, the root cause is in Fluentd or your network. If the first one reproduces this issue, Fluency has a problem. If neither one reproduces this issue, it's possible the way you use Fluency in your application is related.

**Comment by jondoe1337** [comment]
Alright I let the 1) test-driver run for two hours now and I see the following:

```
# ss -n | grep logging-server
tcp    ESTAB      0      39        ::ffff:client:41417  ::ffff:logging-server:24224 
```
lsof shows the same connection but 34 lines duplicated...

On the server-side it shows:
```
tcp    ESTAB      0      0               logging-localip:24224   client:34852 
tcp    ESTAB      0      0               logging-localip:24224   client:35808 
tcp    ESTAB      0      0               logging-localip:24224   client:34899 
tcp    ESTAB      0      0               logging-localip:24224   client:47355 
tcp    ESTAB      0      0               logging-localip:24224   client:34285 
tcp    ESTAB      0      0               logging-localip:24224   client:33359 
tcp    ESTAB      0      0               logging-localip:24224   client:35377 
tcp    ESTAB      0      0               logging-localip:24224   client:41417 
tcp    ESTAB      0      0               logging-localip:24224   client:33320 
```
lsof shows the same connection but 9 lines

I will also check the other thing...

What I just noticed is, that the logging server is also in a NAT environment. It is a Azure Cloud server with a public IP. But the public IP is also not listed in the /etc/network/interfaces.

I don't like to resolve this, but I would guess it is not a good idea to use NAT in this particular scenario.

BTW: The client is hosted on a softlayer server (without NAT).
