### ISSUE TITLE
Introduce strict buffer retention size property

### ISSUE THREAD

**Issue by sokomishalov** [komamitsu/fluency#283]
It would be useful in the case of using fluent-bit with low default buffering settings.

**Comment by komamitsu** [comment]
What do you mean by "strict buffer retention size"?

**Comment by sokomishalov** [comment]
Thanks for the quick reply!
Well, I've found your reply [here](https://github.com/komamitsu/fluency/issues/170#issuecomment-695167113) that buffer chunk retention size is not actually strict so it has to be set a bit less than it actually could be and does not even save us from exceeding fluentd/fluent-bit buffering limit. 
So I suppose it could be useful if it is implementable at all.

**Comment by komamitsu** [comment]
I see. I got the point.

Yes. It sounds a good improvement. I would try it later.

**Comment by komamitsu** [comment]
Sorry, I may have read your comment wrongly. Setting BufferChunkRetentionSize to less than the buffer limit of Fluentd / Fluent Bit should work. I'll update Fluency README to mention the relationship between Fluentd / Fluent Bit buffer size and Fluency's BufferChunkRetentionSize.

**Comment by komamitsu** [comment]
Ah, I remember that indeed there is room to improve to make it more strict. Let me try.
