### ISSUE TITLE
Provide an additional way to configure the RecordFormatter when using the FluencyBuilderForFluentd

### ISSUE THREAD

**Issue by frosiere** [komamitsu/fluency#365]
In some situations, it may be required to customize the _RecordFormatter_ (additional Jackson modules, etc). There is currently a method taking a _RecordFormatter_ and an _Ingester_ (_FluencyBuilderForFluentd#buildFromIngester(RecordFormatter recordFormatter, Ingester ingester)_) which is nice is some cases.

The configuration becomes complex and requires a bunch of copy/paste when used in combination with the [_FluencyLogbackAppender_](https://github.com/sndyuk/logback-more-appenders/blob/master/src/main/java/ch/qos/logback/more/appenders/FluencyLogbackAppender.java)

Therefore, to ease the configuration, and dissociate the customization of the recorder from the ingester, it would be great to update the _FluencyBuilderForFluentd_ as follow

```
public class FluencyBuilderForFluentd {
   ...
   private RecordFormatter recordFormatter = new FluentdRecordFormatter(); // default recorder like now - see buildRecordFormatter
   
   public void setRecordFormatter(RecordFormatter recordFormatter) {
      this.recordFormatter = recordFormatter;
   }
   ...
}
```

At appender level, this would allow the following customization

```
public class CustomFluencyLogbackAppender extends FluencyLogbackAppender<ILoggingEvent> {

    @Override
    protected FluencyBuilderForFluentd configureFluency() {
        final var builder = super.configureFluency();
        final var config = new FluentdRecordFormatter.Config();
        config.setJacksonModules(Lists.newArrayList(
                new Jdk8Module(),
                new JavaTimeModule()
        ));
        builder.setRecordFormatter(new FluentdRecordFormatter(config));
        return builder;
    }
}
```

Any other suggestions to support this use case would be appreciated.

Thanks a lot for your help and for the Fluency support.

**Comment by komamitsu** [comment]
@frosiere Even with `setRecordFormatter()`, it looks still a bit complicated to inject Jackson modules. And I have another concern that a wrong RecordFormatter can be passed (e.g. passing JsonlRecordFormatter to FluencyBuilderForFluentd.)

How about this?

```java
public class CustomFluencyLogbackAppender extends FluencyLogbackAppender<ILoggingEvent> {

    @Override
    protected FluencyBuilderForFluentd configureFluency() {
        final var builder = new FluencyBuilderForFluentd();
        // "setJacksonModulesForRecordFormatter" is too verbose...?
        builder.setJacksonModulesForRecordFormatter(Lists.newArrayList(
            new Jdk8Module(),
            new JavaTimeModule()
        ));
        return builder;
    }
}
```

**Comment by frosiere** [comment]
Good point, proposal is nice and prevents using a wrong formatter. 

An alternative would be a method taking the record formatter config like 
`builder.setRecordFormatterConfig(RecordFormatter.Config config)`

Thanks a lot for your reply.

**Comment by komamitsu** [comment]
Yeah, `setRecordFormatter()` is more powerful. I'll go with it.
I'm a bit busy these days and it would take some time until the feature is released.

**Comment by frosiere** [comment]
Perfect. If I drop a PR, would it be possible to have a 2.6.1 release soon?
Thanks a lot.
