### ISSUE TITLE
Fluency - emit() failed due to buffer full. Flushing buffer. Please try again.

### ISSUE THREAD

**Issue by fly7632785** [komamitsu/fluency#496]
Hi, I got this problem, how to deal with it, please. 
![企业微信截图_16549236787939](https://user-images.githubusercontent.com/10276266/173336990-82fb4056-f343-4e26-814c-129ce4e2ffcc.png)
It is hitting these logs a lot all the time.
![image](https://user-images.githubusercontent.com/10276266/173337879-d93d9cce-5722-4e40-80d5-8f6b37919df3.png)
![image](https://user-images.githubusercontent.com/10276266/173337940-3d84a6b1-b4c8-43c4-b7c7-183135ad7c99.png)
![image](https://user-images.githubusercontent.com/10276266/173338026-65e1b271-3505-4f5d-b605-4103f34d6133.png)

Then checked source, maybe it append the data which its size is more than MaxBufferSize？
How can it append the data which is more than MaxBufferSize(256M) one time ？

Looking forward to getting your reply

Thank you

Here is config.
`
 
    <appender name="FLUENCY_SYNC" class="ch.qos.logback.more.appenders.FluencyLogbackAppender">
        
        
        <tag>${applicationName}</tag>
        

        
        <remoteHost>${fluentdAddr}</remoteHost>
        <port>24224</port>

        

        
        
        <additionalField>
            <key>env</key>
            <value>${profile}</value>
        </additionalField>

        
        <ackResponseMode>true</ackResponseMode>
        
        <bufferChunkInitialSize>2097152</bufferChunkInitialSize>
        <bufferChunkRetentionSize>16777216</bufferChunkRetentionSize>
        <maxBufferSize>268435456</maxBufferSize>
        <bufferChunkRetentionTimeMillis>1000</bufferChunkRetentionTimeMillis>
        <connectionTimeoutMilli>5000</connectionTimeoutMilli>
        <readTimeoutMilli>5000</readTimeoutMilli>
        <waitUntilBufferFlushed>30</waitUntilBufferFlushed>
        <waitUntilFlusherTerminated>40</waitUntilFlusherTerminated>
        <flushAttemptIntervalMillis>200</flushAttemptIntervalMillis>
        <senderMaxRetryCount>12</senderMaxRetryCount>
        
        <useEventTime>true</useEventTime>
        <sslEnabled>false</sslEnabled>
        
        <jvmHeapBufferMode>false</jvmHeapBufferMode>
        
        <flattenMapMarker>false</flattenMapMarker>
        
        <markerPrefix></markerPrefix>

        
        <encoder>
            <pattern><![CDATA[%-5level %logger{50}#%line %message]]></pattern>
        </encoder>

        
        <messageFieldKeyName>msg</messageFieldKeyName>

    </appender>
    
     <appender name="FLUENCY" class="ch.qos.logback.classic.AsyncAppender">
        
        <queueSize>999</queueSize>
        
        <neverBlock>true</neverBlock>
        
        <maxFlushTime>1000</maxFlushTime>
        <appender-ref ref="FLUENCY_SYNC"/>
    </appender>
`

**Comment by fly7632785** [comment]
@xerial @komamitsu @jglick @mach-kernel    please help

**Comment by komamitsu** [comment]
@fly7632785 

> Then checked source, maybe it append the data which its size is more than MaxBufferSize？
> How can it append the data which is more than MaxBufferSize(256M) one time ？

Do you think you appended such a huge log data at once?

If no, I guess the following things happened
- Your Fluency instance tried to send log data to your Fluentd
- But it kept to fail due to network issue or something
- The unsent data were buffered
- The internal buffer pool in Fluency got empty
- The buffer full exception occurred

Probably some network error log messages were output before the buffer full error messages.

And it's hard to support you because you use `FluencyLogbackAppender` and I'm not familiar with it. It would be great if you create a minimum code w/o `FluencyLogbackAppender` to reproduce this issue.

**Comment by fly7632785** [comment]
@komamitsu   thank you for you reply.
I am sure there is not a so big log data ( more than 256M)，I think it maybe that the unsent data are accumulated into a big data, so it is keeping failing.  Is it possible about that?

**Comment by fly7632785** [comment]
![image](https://user-images.githubusercontent.com/10276266/173481119-982e90c6-81b8-4f7f-8a6d-5e899402588f.png)
@komamitsu 
the code has a comment, what's that meaning? And is it possible that there is a problem about this code ?

**Comment by fly7632785** [comment]
I think  I figured it out.
There is a problem about  "flushInternal" method.

I had a test which occurred the problem.
Here is the config:
```
<bufferChunkInitialSize>200470</bufferChunkInitialSize>

        <bufferChunkRetentionSize>2000470</bufferChunkRetentionSize>

        <maxBufferSize>6000470</maxBufferSize>

        <bufferChunkRetentionTimeMillis>1000</bufferChunkRetentionTimeMillis>
```
bufferChunkInitialSize 200K
bufferChunkRetentionSize  2000K
maxBufferSize  6000K

set fluentd wrong config (mock error)
```
       <remoteHost>${fluentdAddr}</remoteHost>

        <port>24225</port>     
```

loop print log 
```
 for (int i = 0; i < 10000000L; i++) {
            log.info("logger，test:");
 }
```

run for a while, it occurs.
![image](https://user-images.githubusercontent.com/10276266/173536179-c293c3a3-cc9e-41c1-aa07-08d467991af0.png)



Then I track the source to find the problem.

normalizedBuffersize  is 400K
allocatedSize  is 5613K
maxBufferSize is 6000K

normalizedBuffersize  +  allocatedSize   > maxBufferSize   
then it will releaseBuffers() and  throw an error later.
It stands to reason that the allocatedSize will be released next time, it will run normally. 



![image](https://user-images.githubusercontent.com/10276266/173536885-f9ee9ec3-47c4-4fd3-8c91-87ade5527477.png)
![image](https://user-images.githubusercontent.com/10276266/173537025-bc44a178-1c00-424c-bb92-d69eca8f5a90.png)

but  the allocatedSize  is not be released.
![image](https://user-images.githubusercontent.com/10276266/173540368-9aaa8a0d-c7f1-4d4f-b67d-18bfca6e2689.png)

then it will print the log '[AsyncAppender-Worker-FLUENCY] ERROR org.komamitsu.fluency.Fluency - emit() failed due to buffer full. Flushing buffer. Please try again...',  

![image](https://user-images.githubusercontent.com/10276266/173538980-4d2b3daf-5709-42d6-944a-2c321f0a8efd.png)

so  go into a cycle  and keep printing the log.

**but why the allocatedSize  is not be released?**

![image](https://user-images.githubusercontent.com/10276266/173537234-c9b970bf-9498-4ab5-ad12-c094f29a1a0e.png)

cause  ingester.ingest(tag, dataBuffer) error (fluentd error),  
bufferPool.returnBuffer(flushableBuffer.getByteBuffer())  doesn't run, 
the bufferPool  can't  offer the bytebuffer, so the allocatedSize  can't be released

if fluentd error can't recover， it will keep printing


Here is the reasion I found, you can test it 

Thank you again.
