### ISSUE TITLE
Heartbeater is disabled by default although doc says the opposite

### ISSUE THREAD

**Issue by jondoe1337** [komamitsu/fluency#53]
I was a little bit confused by thinking that the Heartbeat functionality is enabled by default (as the Readme.md) says, but when I did some investigation i found out that the construction is disabled by default:

`private Heartbeater.Instantiator heartbeaterConfig;   // Disabled by default`
--> org.komamitsu.fluency.sender.TCPSender.Config (line 225)

Is there a technical background for that?

**Comment by komamitsu** [comment]
`TCPSender` doesn't use any heartbeat by default. But if you set up a Fluency using `Fluency.defaultFluency(List<InetSocketAddress> servers, Config config)`, `TCPSender` uses `TCPHeartbeater` internally for quick failover.

**Comment by jondoe1337** [comment]
Is ist an issue now or not?

**Comment by jondoe1337** [comment]
What also looks strange is the Heartbeat implementation itself:
`org.komamitsu.fluency.sender.heartbeat.TCPHeartbeater.invoke()`
Why are you opening and closing a SocketChannel? This operation is very expensive, instead of just activating a keep-alive.

**Comment by komamitsu** [comment]
@jondoe1337 

> Is it an issue now or not?

I don't think it's an issue. But if you want to use a heartbeat even when using only one Fluentd, the way you wrote to construct a Fluency instance should work. Maybe I'd better make `org.komamitsu.fluency.Fluency#defaultFluency(host, port)` use a heartbeat.

> Why are you opening and closing a SocketChannel? This operation is very expensive

It's the same way as Fluentd's `out_forward` plugin. How much is it expensive at 1 sec interval comparing to TCP keep alive?

**Comment by jondoe1337** [comment]
Okay, you are right - I might have used it the wrong way.
