### ISSUE TITLE
How to synchronous flush to Fluentd ?

### ISSUE THREAD

**Issue by gjobin** [komamitsu/fluency#54]
Hi, I was looking for the way to activate synchronous flush to Fluentd and it did not find how in the documentation nor by looking at the Config class.

Could you please tell me what configuration controls that ?

Thank you.
Guillaume

**Comment by komamitsu** [comment]
@gjobin Sorry for my late reply.
You can create a `Fluency` instance that synchronously flushes data like this
```
    // Same as: TCPSender sender = new TCPSender.Config().setHost("localhost").setPort(24224).createInstance();
    TCPSender sender = new TCPSender.Config().createInstance();
    Fluency fluency = new Fluency.Builder(sender).setFlusherConfig(new SyncFlusher.Config()).build();
```
I'll add an example code snippet like the above to README later. Maybe I should add a configuration API to `Fluency.defaultFluency()` for `AsyncFlusher`.

**Comment by gjobin** [comment]
Thank you for the reply.
Sure A configuration API would do the job, but at least I can now do it manually.

**Comment by jklap** [comment]
I've been testing sync flushing and see some weird behavior that I can't explain looking at the code.

I've configured Fluency as above-- no other options. I've then set up a thread that pushes ~200 small messages into emit() per minute every minute. But fluentd isn't receiving them in a timely manner. I added a file output to fluentd and I've been watching it for 15 minutes now with no data. Is this expected?

**Comment by komamitsu** [comment]
@jklap With SyncFlusher, Fluency doesn't flush its buffers automatically. Can you call `Fluency#flush` when you want to flush the buffers?

**Comment by komamitsu** [comment]
I'm closing this issue. The issue @jklap said above is being discussed on https://github.com/komamitsu/fluency/issues/64.

**Comment by jklap** [comment]
That is curious-- both emit() and Fluency#flush() call flushInternal() which calls buffer.flush() depending on the flag force or time passed or buffer threshold-- so am I reading this wrong as it does seem like SyncFlusher should flush during calls to emit()? And I'm not calling Fluency#flush() but it is flushing-- anywhere between 45 and 90 minutes consistently with that number of messages.

**Comment by komamitsu** [comment]
Fluency flushes the buffers when it tried to append an event to the buffers and runs into BufferFullException. https://github.com/komamitsu/fluency/blob/master/src/main/java/org/komamitsu/fluency/Fluency.java#L163

You kept to append events calling `emit()` without a call of `flush()` and the Fluency caught BufferFullException. As a result, the Fluency flushed the buffers the several ten minutes later, I think.

**Comment by jklap** [comment]
Wouldn't the flushInternal() called as part of the emit() force a flush based on time or threshold? Or am misunderstanding that logic?

**Comment by jklap** [comment]
emit(), upon catching the BufferFullException logs that fact at an error level before calling flush()-- I don't see that error message in my log files. But even so, both emit() and flush() end up calling flushInternal() which should trigger not only on the forced flag but also on time or threshold, yes?

**Comment by komamitsu** [comment]
Oops. Sorry, it looks like missed another path. Let me check...
