### ISSUE TITLE
Support sync flush in async flusher

### ISSUE THREAD

**Issue by jklap** [komamitsu/fluency#64]
The idea would be a max buffer size (or time delay) before the async flusher switches to a sync flush upon an emit() and blocks return until the pending buffer size decreases below a defined threshold.

The scenario I ran into was processing a large file (several million lines, each converted into a single emit). I was processing data faster then the flusher was flushing it in the background and hence quickly ran into OOM issues (this is a small footprint app).

While (I think) the SyncFlusher has this type of check built in the SyncFlusher also has the issue that widely spaced emit calls could lead to a delay in a message send (ie push a bunch of messages in quickly yet still under the flush interval and buffer threshold and then stop calling emit()). Those messages will sit there forever until another emit() occurs.

**Comment by komamitsu** [comment]
@jklap When using SyncFlusher, Fluency doesn't flush its buffers automatically. Call Fluency#flush when you want to flush the buffers.

As for OOM issue with a small footprint app you're concerned, you can configure the memory buffer size and thresholds in Fluency. With a proper configuration of memory buffer, AsyncFlusher which is a default flusher works even in a small footprint app, I think.

**Comment by jklap** [comment]
A quick eyeball of the code and it looks like Fluency will end up throwing an exception requiring the caller to handle where as I'm suggesting here that it blocks the caller when the buffer is full

**Comment by komamitsu** [comment]
Fluency usually flushes buffered events automatically with SyncFlusher or manually calling `flush()` with AsyncFlusher before getting buffer full.

**Comment by komamitsu** [comment]
Hmm.. I had a wrong idea on SyncFlusher. It shouldn't require a call of `flush()` manually. And I found a kind of bug that happens when adding small events repeatedly at a short interval. I'll fix the issue.

**Comment by komamitsu** [comment]
@jklap I fixed the bug Fluency with SyncFlusher doesn't flush buffered events without manually calling `flush()` at https://github.com/komamitsu/fluency/pull/65

And released the fix as version 1.3.0 that is going to be available in a few hours. Can I ask you to try the new version? I think the issues you're facing will be solved with the change.

Sorry for my wrong explanations above and at https://github.com/komamitsu/fluency/issues/54 and thanks for your reporting.

**Comment by jklap** [comment]
Sounds good-- I'll update to 1.3 tomorrow and test!

On Tue, May 2, 2017 at 12:12 PM, Mitsunori Komatsu <notifications@github.com

**Comment by jklap** [comment]
I've been running it for 2 days and it looks good!

**Comment by komamitsu** [comment]
@jklap Glad to hear that!
It seems the trouble you were facing was due to the problem I fixed at v1.3.0, so I'm closing this issue for now. If you still have any trouble on this issue, feel free to reopen it.
