### ISSUE TITLE
Return Error instead of Discarding Data

### ISSUE THREAD

**Issue by obokaiwele** [komamitsu/fluency#67]
Scenario:
1. Fluentd daemon is not running, so logger cannot connect.
2. No file backup is configured, so filebackup == null
3. Retries to connect to daemon have been exceeded so failure strategy is to save buffer to filebackup
4. Here the logger silently discards the data. It should instead return IOException, so that application can handle the situation.

https://github.com/komamitsu/fluency/blob/806cad7c1b76a4298f1b12f13b4c1b21015d025b/src/main/java/org/komamitsu/fluency/buffer/Buffer.java#L75

Similarly, here it simply logs an error with AsyncFlusher instead or actually returning the error
https://github.com/komamitsu/fluency/blob/6a9e8d2894d6793103607e26dee4fc4ed45b49ee/src/main/java/org/komamitsu/fluency/flusher/AsyncFlusher.java#L38

**Comment by komamitsu** [comment]
AsyncFlusher runs in background thread. So there is no straight way to return an error of flushing data to the user application. Instead introducing an error handler that has a callback function would work. With it, the user application can pass a custom error handler to Fluency and Fluency call the callback function of the error handler to notify a send error to the user application. I'll take care of the feature later.

RE: the backup configuration of Fluency, it is just to save buffers in memory to file when Fluency is closing not for failures of flushing data.

BTW, Fluentd being down should be detected by a monitoring system not by a Fluentd logger for robustness.

**Comment by komamitsu** [comment]
I'm going to support custom error handlers on https://github.com/komamitsu/fluency/issues/66

**Comment by komamitsu** [comment]
@obokaiwele FYI: Fluency 1.4.0 supports custom error handler and you can detect a send error with that.

**Comment by obokaiwele** [comment]
@komamitsu Is there a way to get the payload that could not be emitted while handling the error?
My use case is to try to emit via Fluency, if that fails, then log the same data to system journald.
