### ISSUE TITLE
Support TLS

### ISSUE THREAD

**Issue by cosmo0920** [komamitsu/fluency#69]
Fluentd v1 protocol specification says that "MAY be able to establish SSL/TLS session on that connection."

ref: https://github.com/fluent/fluentd/wiki/Forward-Protocol-Specification-v1#network-transport-protocol

It would be nice to have SSL/TLS handling in Fluency.

**Comment by komamitsu** [comment]
Thanks for letting me know that.
That sounds interesting. I'll take care of it when I get a chance (I'm a bit tied up with other issues now.)

BTW, I'm not sure this feature is so important and useful. In which situation is this feature important and useful?

**Comment by cosmo0920** [comment]
@okkez and I use this library in [kafka-connect-fluentd](https://github.com/fluent/kafka-connect-fluentd) to send kafka event into Fluentd (Fluentd Sink).
We plan to support TLS forwarding in Fluentd Sink.

**Comment by komamitsu** [comment]
I see. It sounds cool.
