### ISSUE TITLE
Add an emit method to output MessagePack encoded data directly

### ISSUE THREAD

**Issue by xerial** [komamitsu/fluency#72]
The current emit method requires using `Map<String, Object>`, and then msgpack-jackson encodes this Map value into a msgpack byte array:
https://github.com/komamitsu/fluency/blob/master/src/main/java/org/komamitsu/fluency/buffer/PackedForwardBuffer.java#L143

If the application can generate msgpack `map<string, msgpack value>` data in advance, this step can be optimized. For example, we can write a converter of zipkin or opentracing data into msgpack, then use Fluency for sending these application tracing data somewhere through fluentd.

@komamitsu 
How about adding such low-level advanced methods like this?
`emit(String tag, byte[] mapValue)`
`emit(String tag, byte[] mapValue, int offset, int len)`
`emit(String tag, ByteBuffer mapValue)`

**Comment by komamitsu** [comment]
Sounds nice 👍 

`emit(String tag, MapValue mapValue)` might be useful too.

**Comment by komamitsu** [comment]
This feature is available with https://github.com/komamitsu/fluency/pull/73
