### ISSUE TITLE
ackResponseMode true - SocketReadTimeout causes infinite retry 

### ISSUE THREAD

**Issue by jeevamanivel** [komamitsu/fluency#741]
Hi,

Our log flows through Fluency -> Fluentd Forwarder -> Fluentd Aggregator
We have set ackResponseMode to true in our fluency configuration. During high load - because of some issues, fluentd forwarder receives events successfully, but the response is delayed which causes SocketReadTimeout in Fluency.

This causes infinite retry till fluency receives response(We have seen max 755 retries - Fluentd forwarder received all these events successfully, hence 754 duplicates). Can we have configuration to set upperbound on this retry?

Thanks,
Jeeva

**Comment by komamitsu** [comment]
Sorry for the delayed response. I think this works.

```java
builder.setReadTimeoutMilli(10000);
```

See https://github.com/komamitsu/fluency#socket-configuration for details
