### ISSUE TITLE
Data loss in the Buffer after throwing an IOException  inside `moveRetentionBufferToFlushable()` method

### ISSUE THREAD

**Issue by valiparsa** [komamitsu/fluency#743]
We have observed a situation where chunks in the Buffer cannot be flushed due to earlier InterruptedException while emitting the data and the data in the Buffer is lost. Here are the steps:

1. `fluency.emit()` method is executed to emit data into the Buffer. 
1. As Buffer is full a `BufferFullException` [is thrown with such a message "failed due to buffer full. Flushing buffer. Please try again..."](https://github.com/komamitsu/fluency/blob/2.7.0/fluency-core/src/main/java/org/komamitsu/fluency/Fluency.java#L200)
1. Sleep is introduced in the consumer code to sleep until Buffer gets flushed to be ready to accept more chunks.
1. `Thread.currentThread.interrupt()` throws an interruptedException due to the long sleep.
1. Buffer is flushed and is ready to accept new Chunks.
1. `fluency.emit()` method is executed without any problems for more chunks until the Buffer gets full again.
1. Buffer is full again and [moveRetentionBufferToFlushable](https://github.com/komamitsu/fluency/blob/2.7.0/fluency-core/src/main/java/org/komamitsu/fluency/buffer/Buffer.java#L332C18-L332C48) method is called to prepare the Buffer to be flushed.
1. [flushableBuffers.put(new TaggableBuffer(tag, buffer.getByteBuffer()));](https://github.com/komamitsu/fluency/blob/2.7.0/fluency-core/src/main/java/org/komamitsu/fluency/buffer/Buffer.java#L338) detects that the InterruptedException happened earlier and re-throws the InterruptedException.
1. Then instead of propagating the InterruptedException an [IOException](https://github.com/komamitsu/fluency/blob/2.7.0/fluency-core/src/main/java/org/komamitsu/fluency/buffer/Buffer.java#L342) is thrown, which is not the main problem we faced but unusual behaviour.
    ```
    java.lang.InterruptedException
	    at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1261)
	    at java.base/java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:317)
	    at java.base/java.util.concurrent.LinkedBlockingQueue.put(LinkedBlockingQueue.java:330)
	    at org.komamitsu.fluency.buffer.Buffer.moveRetentionBufferToFlushable(Buffer.java:338)
    Caused: java.io.IOException: Failed to move retention buffer due to interruption
	    at org.komamitsu.fluency.buffer.Buffer.moveRetentionBufferToFlushable(Buffer.java:342)
	    at org.komamitsu.fluency.buffer.Buffer.moveRetentionBufferIfNeeded(Buffer.java:311)
	    at org.komamitsu.fluency.buffer.Buffer.loadDataToRetentionBuffers(Buffer.java:208)
	    at org.komamitsu.fluency.buffer.Buffer.appendMapInternal(Buffer.java:253)
	    at org.komamitsu.fluency.buffer.Buffer.append(Buffer.java:280)
	    at org.komamitsu.fluency.Fluency.lambda$emit$1(Fluency.java:61)
	    at org.komamitsu.fluency.Fluency$Emitter.emit(Fluency.java:197)
	    at org.komamitsu.fluency.Fluency.emit(Fluency.java:61)
    ```
1. Before [flushableBuffers.put(...) method](https://github.com/komamitsu/fluency/blob/2.7.0/fluency-core/src/main/java/org/komamitsu/fluency/buffer/Buffer.java#L337) throws an InterruptedException [Buffer was flipped](https://github.com/komamitsu/fluency/blob/2.7.0/fluency-core/src/main/java/org/komamitsu/fluency/buffer/Buffer.java#L337) which causes data loss in the next steps.

The more correct behaviour would be to replace 

```
buffer.getByteBuffer().flip();
```
 
by
 
```
buffer.getByteBuffer().duplicate().flip();
```
 
duplicate() creates a shallow copy, i.e. the underlying data array is the same but is has independent position and limit.
 
In case of an `InterruptedException` the original ByteBuffer stays untouched and the data is not lost.

**Comment by komamitsu** [comment]
@valiparsa Thanks for reporting the issue! I'll add a benchmark to easily detect performance degradation and come up with unit tests to reproduce the issue, and then fix it.

**Comment by valiparsa** [comment]
> @valiparsa Thanks for reporting the issue! I'll add a benchmark to easily detect performance degradation and come up with unit tests to reproduce the issue, and then fix it.

Thanks @komamitsu for picking this up.
