### ISSUE TITLE
What does setSenderMaxRetryCount ?

### ISSUE THREAD

**Issue by thiennguyen1308** [komamitsu/fluency#83]
Hi there, my config is:
              fluency = Fluency.defaultFluency(MyConstants.FLUENTD_IP, MyConstants.FLUENTD_PORT,
                        new Fluency.Config()
                        .setSenderMaxRetryCount(0)
                        .setSenderErrorHandler(new SenderErrorHandler() {
                            @Override
                            public void handle(Throwable e) {
                                System.out.println("error");
                                fluentdActive = false;
                            }
                        })
                );

when i set setSenderMaxRetryCount =1, it keeps printing out "error" so many times, but when i set setSenderMaxRetryCount , it only printout just 1 times. I test with 1 array contains only 1 element.

**Comment by komamitsu** [comment]
`setSenderMaxRetryCount()` is for underlying TCP sender. Fluency has also `AsyncFlusher` that sends buffered data that is failed to be sent periodically. So even if you call `setSenderMaxRetryCount` with 0 or 1, `AsyncFlusher` tries to flush buffer periodically. I think you can see an error message `RetryableSender$RetryOverException: Sending data was retried over` if you print the Throwable in the callback method.

If you set `Fluency.Config#setFlushIntervalMillis` to 10 seconds, I think you don't see the error frequently.

**Comment by komamitsu** [comment]
Closing this issue. If you still have any trouble on this issue, feel free reopen it.
