### ISSUE TITLE
Add size to forward payload.

### ISSUE THREAD

**Issue by repeatedly** [komamitsu/fluency#85]
Fluentd v1 accepts `size` in forward payload.
This reduces unnecessary deserialization when plugin need to get event stream size.

https://github.com/fluent/fluentd/blob/bc77372d0514964690e0e1a43c487e5cb7ef9033/lib/fluent/plugin/out_forward.rb#L611

**Comment by komamitsu** [comment]
@repeatedly Fluency already sends a buffer size following a tag name like https://github.com/fluent/fluentd/blob/bc77372d0514964690e0e1a43c487e5cb7ef9033/lib/fluent/plugin/out_forward.rb#L623 outside an option. What's the difference between sizes in/outside an option? Can Fluency send the same value as the existing one in an option?

**Comment by repeatedly** [comment]
Outside an option, fluentd need to deserialize incoming object and it needs CPU resource for lots of messages.
Inside an option, fluentd can skip deserialization.

**Comment by komamitsu** [comment]
I see.
Addressed this at https://github.com/komamitsu/fluency/pull/86.

And I saw a `size` from Fluency was expectedly passed to https://github.com/fluent/fluentd/blob/bc77372d0514964690e0e1a43c487e5cb7ef9033/lib/fluent/plugin/in_forward.rb#L293
